'use client';
import {useEffect,useMemo,useState} from 'react';
type Service={id:string;version?:number;name:string;category:string;price:number|null;durationMinutes:number|null};
type Slot={start_at:string;location_id:string;appointment_segments:Array<{duration_minutes:number;service_variation_id:string;service_variation_version:number;team_member_id:string}>};
const BRAND={name:process.env.NEXT_PUBLIC_BUSINESS_NAME||'FloBooking Demo',location:process.env.NEXT_PUBLIC_BUSINESS_LOCATION||'Adelaide, SA',timezone:process.env.NEXT_PUBLIC_TIMEZONE||'Australia/Adelaide',currency:process.env.NEXT_PUBLIC_CURRENCY||'AUD',locale:process.env.NEXT_PUBLIC_LOCALE||'en-AU',logo:process.env.NEXT_PUBLIC_LOGO_URL||'',website:process.env.NEXT_PUBLIC_WEBSITE_URL||'',instagram:process.env.NEXT_PUBLIC_INSTAGRAM_URL||'',phone:process.env.NEXT_PUBLIC_PHONE||'',email:process.env.NEXT_PUBLIC_EMAIL||'',policy:process.env.NEXT_PUBLIC_BOOKING_POLICY||'Changes and cancellations are subject to the business cancellation policy.'};
function money(n:number|null){return n===null?'POA':n===0?'Free':new Intl.NumberFormat(BRAND.locale,{style:'currency',currency:BRAND.currency,maximumFractionDigits:0}).format(n)}
function duration(n:number|null){if(!n)return'Ask us';const h=Math.floor(n/60),m=n%60;return h?`${h}h${m?` ${m}m`:''}`:`${m}m`}
function dateKey(iso:string){const p=new Intl.DateTimeFormat('en-CA',{timeZone:BRAND.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(iso));const v=(x:string)=>p.find(i=>i.type===x)?.value;return `${v('year')}-${v('month')}-${v('day')}`}
function dateText(value:string|Date,full=false){return new Intl.DateTimeFormat(BRAND.locale,{timeZone:value instanceof Date?'UTC':BRAND.timezone,weekday:full?'long':'short',day:'numeric',month:full?'long':'short'}).format(value instanceof Date?value:new Date(value))}
function timeText(iso:string){return new Intl.DateTimeFormat(BRAND.locale,{timeZone:BRAND.timezone,hour:'numeric',minute:'2-digit'}).format(new Date(iso))}
export default function Booking(){
 const [services,setServices]=useState<Service[]>([]),[selected,setSelected]=useState<Service[]>([]),[slots,setSlots]=useState<Slot[]>([]);const [category,setCategory]=useState(''),[step,setStep]=useState(1),[day,setDay]=useState(''),[slot,setSlot]=useState<Slot|null>(null);const [loading,setLoading]=useState(true),[searching,setSearching]=useState(false),[booking,setBooking]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState<any>(null);const [customer,setCustomer]=useState({givenName:'',familyName:'',phone:'',email:''}),[note,setNote]=useState('');
 useEffect(()=>{fetch('/api/square/services').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setServices(d.services);setCategory(d.services[0]?.category||'')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const categories=useMemo(()=>[...new Set(services.map(s=>s.category))],[services]);const visible=services.filter(s=>s.category===category);const totals=useMemo(()=>selected.reduce((a,s)=>({price:a.price+(s.price||0),mins:a.mins+(s.durationMinutes||0)}),{price:0,mins:0}),[selected]);
 useEffect(()=>{if(!selected.length){setSlots([]);return}const control=new AbortController(),timer=setTimeout(async()=>{setSearching(true);setError('');setDay('');setSlot(null);const start=new Date(),end=new Date();end.setDate(end.getDate()+32);try{const r=await fetch('/api/square/availability',{method:'POST',headers:{'Content-Type':'application/json'},signal:control.signal,body:JSON.stringify({serviceVariationIds:selected.map(s=>s.id),startAt:start.toISOString(),endAt:end.toISOString()})});const d=await r.json();if(!r.ok)throw Error(d.error);setSlots(d.availabilities||[])}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{if(!control.signal.aborted)setSearching(false)}},220);return()=>{clearTimeout(timer);control.abort()}},[selected]);
 const days=useMemo(()=>{const map:Record<string,Slot[]>={};slots.forEach(s=>(map[dateKey(s.start_at)]||=[]).push(s));return map},[slots]);const dayKeys=Object.keys(days).sort();
 function toggle(s:Service){setSelected(v=>v.some(x=>x.id===s.id)?v.filter(x=>x.id!==s.id):[...v,s]);setSlot(null);setDay('')}
 async function confirm(e:React.FormEvent){e.preventDefault();if(!slot)return;setBooking(true);setError('');try{const r=await fetch('/api/square/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,availability:slot,note})});const d=await r.json();if(!r.ok)throw Error(d.error);setConfirmed({...d.booking,services:selected,total:totals.price,mins:totals.mins,name:customer.givenName})}catch(e:any){setError(e.message)}finally{setBooking(false)}}
 if(confirmed)return <main className="shell confirmed"><Brand/><section className="confirm-card"><i>✓</i><small>Booking confirmed</small><h1>You’re booked.</h1><p>Thanks {confirmed.name}. Your appointment has been added to {BRAND.name}’s live calendar.</p><div className="confirm-grid"><span><small>Date</small><b>{dateText(confirmed.start_at,true)}</b></span><span><small>Time</small><b>{timeText(confirmed.start_at)}</b></span><span><small>Duration</small><b>{duration(confirmed.mins)}</b></span><span><small>Total</small><b>{money(confirmed.total)}</b></span></div><button onClick={()=>location.reload()}>Book another appointment</button><em>{BRAND.policy}</em></section><Footer/></main>;
 return <main className="shell"><Brand/><div className="progress">{[1,2,3,4].map(n=><span className={n<=step?'on':''} key={n}/>)}</div><section className="flow">
  {step===1&&<><Heading n="1" title="Choose your services" text="Select everything you’d like in this appointment."/><nav className="categories">{categories.map(c=><button className={c===category?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</nav><div className="services">{loading?<p>Loading live Square services…</p>:visible.map(s=><button className={selected.some(x=>x.id===s.id)?'selected':''} onClick={()=>toggle(s)} key={s.id}><span><b>{s.name}</b><small>{duration(s.durationMinutes)}</small></span><span><strong>{money(s.price)}</strong><i>{selected.some(x=>x.id===s.id)?'✓':'+'}</i></span></button>)}</div><Action text="Choose a date" disabled={!selected.length} onClick={()=>setStep(2)} summary={`${selected.length} selected · ${duration(totals.mins)} · ${money(totals.price)}`}/></>}
  {step===2&&<><Back onClick={()=>setStep(1)}/><Heading n="2" title="Choose a date" text="Only dates with live availability are shown."/><Summary services={selected}/>{searching?<Loading/>:<div className="dates">{dayKeys.map(k=>{const [y,m,d]=k.split('-').map(Number);return <button onClick={()=>{setDay(k);setStep(3)}} key={k}><small>{new Intl.DateTimeFormat(BRAND.locale,{month:'short',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d)))}</small><b>{d}</b><span>{days[k].length} times</span></button>})}</div>}{!searching&&!dayKeys.length&&!error&&<p className="notice">No availability found in the next 32 days.</p>}</>}
  {step===3&&<><Back onClick={()=>setStep(2)}/><Heading n="3" title="Choose a time" text={day?dateText(new Date(`${day}T00:00:00Z`),true):''}/><div className="times">{(days[day]||[]).map(s=><button onClick={()=>{setSlot(s);setStep(4)}} key={s.start_at}>{timeText(s.start_at)}</button>)}</div></>}
  {step===4&&slot&&<><Back onClick={()=>setStep(3)}/><Heading n="4" title="Your details" text={`Confirm your appointment with ${BRAND.name}.`}/><div className="chosen"><span>{dateText(slot.start_at,true)}</span><b>{timeText(slot.start_at)}</b></div><Summary services={selected}/><form onSubmit={confirm}><div><input required autoComplete="given-name" placeholder="First name" value={customer.givenName} onChange={e=>setCustomer({...customer,givenName:e.target.value})}/><input autoComplete="family-name" placeholder="Last name" value={customer.familyName} onChange={e=>setCustomer({...customer,familyName:e.target.value})}/></div><input required inputMode="tel" autoComplete="tel" placeholder="Mobile" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><input type="email" autoComplete="email" placeholder="Email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/><textarea placeholder="Optional note" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={booking}>{booking?'Booking…':'Confirm booking'}</button></form><p className="policy">{BRAND.policy}</p></>}
  {error&&<p className="notice error">{error}</p>}
 </section><Footer/></main>
}
function Brand(){return <header>{BRAND.website?<a href={BRAND.website}>{BRAND.logo?<img src={BRAND.logo} alt={BRAND.name}/>:<b>{BRAND.name}</b>}</a>:BRAND.logo?<img src={BRAND.logo} alt={BRAND.name}/>:<b>{BRAND.name}</b>}<span>{BRAND.location}</span></header>}
function Footer(){return <footer><span>Live availability via Square</span><nav>{BRAND.instagram&&<a href={BRAND.instagram}>Instagram</a>}{BRAND.phone&&<a href={`tel:${BRAND.phone}`}>Call</a>}{BRAND.email&&<a href={`mailto:${BRAND.email}`}>Email</a>}</nav></footer>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="heading"><small>Step {n} of 4</small><h1>{title}</h1><p>{text}</p></div>}
function Back({onClick}:{onClick:()=>void}){return <button className="back" onClick={onClick}>← Back</button>}
function Action({text,summary,disabled,onClick}:{text:string;summary:string;disabled:boolean;onClick:()=>void}){return <div className="action"><span>{summary}</span><button disabled={disabled} onClick={onClick}>{text} →</button></div>}
function Summary({services}:{services:Service[]}){return <div className="summary">{services.map(s=><span key={s.id}><b>{s.name}</b><strong>{money(s.price)}</strong></span>)}</div>}
function Loading(){return <div className="loading"><i/><span>Checking live availability…</span></div>}
